import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  TrendingUp,
  AlertTriangle,
  ChefHat,
  RefreshCw,
  BrainCircuit,
  Lightbulb,
  Clock,
  ShieldCheck,
} from 'lucide-react';
import { MenuItem, Order, SalesAnalytics, AIInsightsResponse } from '../../types';
import { aiService } from '../../services/aiService';
import { useToast } from '../common/Toast';

interface SmartInsightsSectionProps {
  menuItems: MenuItem[];
  orders: Order[];
  analytics: SalesAnalytics;
}

export const SmartInsightsSection: React.FC<SmartInsightsSectionProps> = ({
  menuItems,
  orders,
  analytics,
}) => {
  const { showToast } = useToast();
  const [insights, setInsights] = useState<AIInsightsResponse | null>(null);
  const [loading, setLoading] = useState(false);

  const fetchInsights = async (forceRefresh: boolean = false) => {
    setLoading(true);
    try {
      const data = await aiService.getManagerAIInsights(menuItems, orders, analytics, forceRefresh);
      setInsights(data);
      if (forceRefresh) {
        showToast(
          data.generatedByAI
            ? 'Fresh insights generated by Gemini AI!'
            : 'Operational insights refreshed (Estimated from past orders).',
          'success'
        );
      }
    } catch {
      const fallback = aiService.calculateStatisticalFallback(menuItems, orders, analytics);
      setInsights(fallback);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInsights(false);
  }, []);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Top Section Header with AI Badge & Refresh Control */}
      <div className="bg-[#25282D] text-white p-6 rounded-3xl border border-white/10 shadow-xl relative overflow-hidden">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="p-1.5 rounded-xl bg-orange-500/20 text-[#FF7A00]">
                <BrainCircuit className="w-5 h-5" />
              </span>
              <h2 className="font-heading font-extrabold text-lg sm:text-xl text-white">
                Predictive Kitchen Intelligence
              </h2>
              {/* Dynamic Badge */}
              <span
                className={`px-2.5 py-0.5 rounded-full text-[11px] font-bold inline-flex items-center gap-1 ${
                  insights?.generatedByAI
                    ? 'bg-purple-500/20 text-purple-300 border border-purple-500/30'
                    : 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                }`}
              >
                <Sparkles className="w-3 h-3" />
                {insights?.sourceLabel || 'AI Canteen Engine'}
              </span>
            </div>
            <p className="text-xs text-slate-300">
              Aggregated historical order patterns, rush telemetry, and inventory velocity analysis.
            </p>
          </div>

          <div className="flex items-center gap-3">
            {insights?.lastUpdated && (
              <span className="text-[11px] text-slate-400 flex items-center gap-1">
                <Clock className="w-3.5 h-3.5 text-slate-500" />
                Last updated: <strong>{insights.lastUpdated}</strong>
              </span>
            )}
            <button
              onClick={() => fetchInsights(true)}
              disabled={loading}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-bold text-white transition-all cursor-pointer disabled:opacity-50"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
              <span>{loading ? 'Analyzing...' : 'Refresh insights'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Loading Skeleton */}
      {loading && !insights ? (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 animate-pulse">
          <div className="bg-white p-6 rounded-3xl h-64 border border-slate-200" />
          <div className="bg-white p-6 rounded-3xl h-64 border border-slate-200" />
          <div className="bg-white p-6 rounded-3xl h-64 border border-slate-200" />
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* 1. Item Demand Prediction */}
          <div className="bg-white p-6 rounded-3xl border border-slate-200/80 shadow-xs space-y-4 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2">
                  <div className="p-2 rounded-xl bg-orange-100 text-[#FF7A00]">
                    <TrendingUp className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="font-heading font-bold text-sm text-slate-900">Item Demand</h3>
                    <p className="text-[10px] text-slate-400">Predicted rush consumption today</p>
                  </div>
                </div>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-orange-50 text-[#FF7A00]">
                  Peak Rush
                </span>
              </div>

              <div className="space-y-3">
                {insights?.itemDemand.map((item, idx) => (
                  <div
                    key={idx}
                    className="p-3.5 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-1.5 text-xs"
                  >
                    <div className="flex items-center justify-between">
                      <h4 className="font-bold text-slate-900">{item.itemName}</h4>
                      <span
                        className={`px-2 py-0.5 rounded-md text-[10px] font-bold ${
                          item.demandLevel === 'Surge'
                            ? 'bg-rose-100 text-rose-700'
                            : 'bg-orange-100 text-orange-700'
                        }`}
                      >
                        {item.demandLevel} Demand
                      </span>
                    </div>

                    <div className="flex items-center justify-between text-[11px]">
                      <span className="font-heading font-extrabold text-[#FF7A00]">
                        ~{item.predictedPortions} portions
                      </span>
                      <span className="text-emerald-600 font-semibold flex items-center gap-1">
                        <ShieldCheck className="w-3 h-3" /> {item.confidence}% confidence
                      </span>
                    </div>

                    <p className="text-[11px] text-slate-500 leading-relaxed pt-0.5">
                      {item.reason}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* 2. Pre-Rush Preparation */}
          <div className="bg-white p-6 rounded-3xl border border-slate-200/80 shadow-xs space-y-4 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2">
                  <div className="p-2 rounded-xl bg-amber-100 text-amber-700">
                    <ChefHat className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="font-heading font-bold text-sm text-slate-900">
                      Pre-Rush Preparation
                    </h3>
                    <p className="text-[10px] text-slate-400">Batch recommendations before peak</p>
                  </div>
                </div>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-amber-50 text-amber-700">
                  Station Prep
                </span>
              </div>

              <div className="space-y-3">
                {insights?.preRushPreparation.map((prep, idx) => (
                  <div
                    key={idx}
                    className="p-3.5 rounded-2xl bg-amber-50/50 border border-amber-200/80 space-y-1.5 text-xs"
                  >
                    <div className="flex items-center justify-between">
                      <h4 className="font-bold text-slate-900">{prep.itemName}</h4>
                      <span className="px-2 py-0.5 rounded-md bg-amber-200 text-amber-900 font-bold text-[10px]">
                        Target: {prep.recommendedPortions} units
                      </span>
                    </div>

                    <p className="text-[11px] font-semibold text-amber-900">
                      ⏱ {prep.preparationInstruction}
                    </p>

                    <div className="flex items-center justify-between text-[10px] text-slate-500 pt-0.5 border-t border-amber-200/60">
                      <span>Window: {prep.targetWindow}</span>
                      <span className="font-semibold text-emerald-700">
                        {prep.confidence}% confidence
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* 3. Food Waste & Leftover */}
          <div className="bg-white p-6 rounded-3xl border border-slate-200/80 shadow-xs space-y-4 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2">
                  <div className="p-2 rounded-xl bg-rose-100 text-rose-700">
                    <AlertTriangle className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="font-heading font-bold text-sm text-slate-900">
                      Food Waste & Leftover
                    </h3>
                    <p className="text-[10px] text-slate-400">Items susceptible to spoilage</p>
                  </div>
                </div>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-50 text-rose-700">
                  Risk Control
                </span>
              </div>

              <div className="space-y-3">
                {insights?.foodWasteLeftover.map((waste, idx) => (
                  <div
                    key={idx}
                    className={`p-3.5 rounded-2xl border space-y-1.5 text-xs ${
                      waste.riskLevel === 'High'
                        ? 'bg-rose-50/50 border-rose-200'
                        : waste.riskLevel === 'Medium'
                        ? 'bg-amber-50/50 border-amber-200'
                        : 'bg-emerald-50/50 border-emerald-200'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <h4 className="font-bold text-slate-900">{waste.itemName}</h4>
                      <span
                        className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                          waste.riskLevel === 'High'
                            ? 'bg-rose-600 text-white'
                            : waste.riskLevel === 'Medium'
                            ? 'bg-amber-600 text-white'
                            : 'bg-emerald-600 text-white'
                        }`}
                      >
                        {waste.riskLevel} Risk • Est. {waste.estimatedLeftover} leftover
                      </span>
                    </div>

                    <p className="text-[11px] text-slate-600 leading-relaxed">
                      {waste.suggestion}
                    </p>

                    <div className="pt-1 border-t border-black/5 flex items-center justify-between text-[10px]">
                      <span className="font-bold text-slate-700 uppercase">
                        Action: {waste.mitigationType}
                      </span>
                      <span className="text-slate-400">Zero-waste policy</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
